# Install packages
install.packages("shiny")
install.packages("shinydashboard")
install.packages("RMySQL")
install.packages("ggplot2")
install.packages("tm")
install.packages("SnowballC")
install.packages("wordcloud")
install.packages("networkD3")
install.packages("igraph")
install.packages("shinyBS")