# Install packages
install.packages("shiny", repos="http://cran.rstudio.com/")
install.packages("shinydashboard", repos="http://cran.rstudio.com/")
install.packages("RMySQL", repos="http://cran.rstudio.com/")
install.packages("ggplot2", repos="http://cran.rstudio.com/")
install.packages("tm", repos="http://cran.rstudio.com/")
install.packages("SnowballC", repos="http://cran.rstudio.com/")
install.packages("wordcloud", repos="http://cran.rstudio.com/")
install.packages("networkD3", repos="http://cran.rstudio.com/")
install.packages("igraph", repos="http://cran.rstudio.com/")
install.packages("shinyBS", repos="http://cran.rstudio.com/")
install.packages("magrittr", repos="http://cran.rstudio.com/")
install.packages("RPostgreSQL", repos="http://cran.rstudio.com/")
